# Generated by Django 6.0.7 on 2026-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
            preserve_default=False,
        ),
    ]
